### ISSUE TITLE
Envío de email confirmando que paso de lista de espera a inscripto

### ISSUE THREAD

**Issue by nicolasmohamed** [cesardmoro/socios-sc#3]
Al momento que el usuario pasa de la lista de espera hacia la lista de inscriptos se le debe enviar un email:

"Hola {usuario}!

Te confirmamos que ya estás inscripto en la capacitación {capacitación} el día {fecha y hora} en {lugar}. En caso de que no puedas asistir te solicitamos que por favor canceles tu inscripción para que otro socio pueda utilizar el cupo disponible.

Asociación Somos Cerveceros
Soy feliz, hago mi propia cerveza"

**Comment by cesardmoro** [comment]
agregada funcionalidad
