### ISSUE TITLE
Subir manual 

### ISSUE THREAD

**Issue by nicolasmohamed** [cesardmoro/socios-sc#4]
Se debe subir el manual a una página HTML para que los socios puedan ver previo a inscribirse. Debe ser pública y no pedir ningún tipo de autenticación.

La url podría ser algo como somoscerveceros.com/socios/como-inscribirse

[Manual usuarios SC.docx](https://github.com/cesardmoro/socios-sc/files/1165641/Manual.usuarios.SC.docx)

**Comment by cesardmoro** [comment]
listo, se puede acceder en: 
http://somoscerveceros.com/socios/manual
